spring:
  cloud:
    config:
      server:
        git:
          uri: http://liuhuanhuan@git.aerohuanyou.com:81/truck-life-cycle/config-files/vmc-config-files.git
          #the git path for search properties file
#          search-paths:
          username: liuhuanhuan
          password: work@1208
  application: com.zh.server.config-server

server:
  port: 8888